// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | FaqSlice
  | NeighborhoodsSlice
  | AverageSlice
  | ScrollTextSlice
  | HeroSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *AveragePrice → Default → Primary*
 */
export interface AverageSliceDefaultPrimary {
  /**
   * Text field in *AveragePrice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: average.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Table field in *AveragePrice → Default → Primary*
   *
   * - **Field Type**: Table
   * - **Placeholder**: *None*
   * - **API ID Path**: average.default.primary.table
   * - **Documentation**: https://prismic.io/docs/fields/table
   */
  table: prismic.TableField;

  /**
   * Image field in *AveragePrice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: average.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AveragePrice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AverageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AverageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AveragePrice*
 */
type AverageSliceVariation = AverageSliceDefault;

/**
 * AveragePrice Shared Slice
 *
 * - **API ID**: `average`
 * - **Description**: Average
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AverageSlice = prismic.SharedSlice<
  "average",
  AverageSliceVariation
>;

/**
 * Item in *Faq → Default → Primary → items*
 */
export interface FaqSliceDefaultPrimaryItemsItem {
  /**
   * questionfaq field in *Faq → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.items[].questionfaq
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  questionfaq: prismic.RichTextField;

  /**
   * answerfaq field in *Faq → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.items[].answerfaq
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answerfaq: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * TitleFAQ field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.titlefaq
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  titlefaq: prismic.RichTextField;

  /**
   * items field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Neighborhoods → Default → Primary → PopularNeighborhoods*
 */
export interface NeighborhoodsSliceDefaultPrimaryPopularneighborhoodsItem {
  /**
   * TitleNeighborhoods field in *Neighborhoods → Default → Primary → PopularNeighborhoods*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: neighborhoods.default.primary.popularneighborhoods[].titleneighborhoods
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titleneighborhoods: prismic.KeyTextField;

  /**
   * IMGNeighborhoods field in *Neighborhoods → Default → Primary → PopularNeighborhoods*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: neighborhoods.default.primary.popularneighborhoods[].imgneighborhoods
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imgneighborhoods: prismic.ImageField<never>;
}

/**
 * Primary content in *Neighborhoods → Default → Primary*
 */
export interface NeighborhoodsSliceDefaultPrimary {
  /**
   * TitleFamousneighborhoods field in *Neighborhoods → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: neighborhoods.default.primary.titlefamousneighborhoods
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  titlefamousneighborhoods: prismic.RichTextField;

  /**
   * PopularNeighborhoods field in *Neighborhoods → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: neighborhoods.default.primary.popularneighborhoods[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  popularneighborhoods: prismic.GroupField<
    Simplify<NeighborhoodsSliceDefaultPrimaryPopularneighborhoodsItem>
  >;
}

/**
 * Default variation for Neighborhoods Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NeighborhoodsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NeighborhoodsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Neighborhoods*
 */
type NeighborhoodsSliceVariation = NeighborhoodsSliceDefault;

/**
 * Neighborhoods Shared Slice
 *
 * - **API ID**: `neighborhoods`
 * - **Description**: Neighborhoods
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NeighborhoodsSlice = prismic.SharedSlice<
  "neighborhoods",
  NeighborhoodsSliceVariation
>;

/**
 * Primary content in *ScrollText → Default → Primary*
 */
export interface ScrollTextSliceDefaultPrimary {
  /**
   * Eyebrow field in *ScrollText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_text.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Text field in *ScrollText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for ScrollText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScrollTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScrollTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScrollText*
 */
type ScrollTextSliceVariation = ScrollTextSliceDefault;

/**
 * ScrollText Shared Slice
 *
 * - **API ID**: `scroll_text`
 * - **Description**: ScrollText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScrollTextSlice = prismic.SharedSlice<
  "scroll_text",
  ScrollTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AverageSlice,
      AverageSliceDefaultPrimary,
      AverageSliceVariation,
      AverageSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimaryItemsItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      NeighborhoodsSlice,
      NeighborhoodsSliceDefaultPrimaryPopularneighborhoodsItem,
      NeighborhoodsSliceDefaultPrimary,
      NeighborhoodsSliceVariation,
      NeighborhoodsSliceDefault,
      ScrollTextSlice,
      ScrollTextSliceDefaultPrimary,
      ScrollTextSliceVariation,
      ScrollTextSliceDefault,
    };
  }
}
