// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  average: dynamic(() => import("./AveragePrice")),
  faq: dynamic(() => import("./Faq")),
  hero: dynamic(() => import("./Hero")),
  neighborhoods: dynamic(() => import("./Neighborhoods")),
  scroll_text: dynamic(() => import("./ScrollText")),
};
